/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oss;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HELLO
 */
public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setPreferredSize(new java.awt.Dimension(787, 1427));

        jPanel1.setLayout(null);

        jButton3.setText("Add Bill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 620, 80, 23);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("ABDK CART");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 10, 275, 64);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 620, 69, 23);

        jTextField7.setEnabled(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(480, 110, 120, 22);

        jLabel7.setText("Bill_id");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 110, 50, 16);

        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(130, 150, 120, 22);

        jTextField4.setEnabled(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(480, 150, 120, 20);

        jLabel5.setText("Customer id");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 150, 80, 16);

        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 620, 120, 23);

        jLabel4.setText("Customer Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 150, 87, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 210, 540, 310);

        jLabel3.setText("Amount");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 560, 44, 20);

        jLabel2.setText("Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 60, 50, 16);

        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(560, 60, 110, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 110, 120, 22);

        jLabel1.setText("Order id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 110, 70, 16);

        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(620, 560, 110, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oss/153243-samsung_galaxy-samsung-galaxy_c8-smartphone-blue-1920x1080.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 800, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel tableModel=null;
        try {
            // TODO add your handling code here:
            String SQL1="Select Distinct O.O_date,C.C_Name,O.C_id\n" +
                    "from orders O,customers C\n" +
                    "where O.C_id=C.C_id and O.O_id="+ Integer.parseInt( jTextField1.getText().trim());
            String SQL2="Select O.P_id,P.P_Name,P.P_price,O.quantity,O.Amount \n" +
                    "from Orders O,Products P\n" +
                    "where O.P_id=P.P_id and O.O_id="+ Integer.parseInt( jTextField1.getText().trim());
            String SQL3="Select Sum(Amount) from orders where O_id="+ Integer.parseInt( jTextField1.getText().trim());
            String SQL4="Select * from Billing";
            ResultSet rs = DB_Part.Query(DB_Part.con, SQL4);
                if (rs.next()) {
                    rs.last();
                    int id = rs.getInt(1) + 1;
                    jTextField7.setText(String.valueOf(id));
                } else {
                    jTextField7.setText("1");
                }
            ResultSet rs1 = DB_Part.Query(DB_Part.con,SQL1);
            while(rs1.next()) {
                jTextField2.setText(rs1.getString(1));
                jTextField4.setText(rs1.getString(2));
                jTextField5.setText(rs1.getString(3));
            }
            ResultSet rs2 = DB_Part.Query(DB_Part.con, SQL2);
            tableModel = DB_Part.buildTableModel(rs2);
            jTable1.setModel(tableModel);

            jTable1.setShowGrid(true);

            jTable1.setShowVerticalLines(true);
            ResultSet rs3 = DB_Part.Query(DB_Part.con,SQL3);
            while(rs3.next()) {
                jTextField3.setText(rs3.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String SQL="INSERT INTO Billing VALUES ('"+jTextField1.getText().trim().toUpperCase()+"','"+jTextField2.getText().trim().toUpperCase()+"','"+jTextField2.getText().trim().toUpperCase()+"','"+jTextField5.getText().trim().toUpperCase()+"','"+jTextField3.getText().trim().toUpperCase()+"')";
            if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField5.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Any field should not be null");
            }
            else{
                try {
                  int ret =DB_Part.UpdateTable(DB_Part.con, SQL);
                  JOptionPane.showMessageDialog(this,"Bill inserted");
                  jTextField1.setText("");
                  jTextField2.setText("");
                  jTextField3.setText("");
                  jTextField4.setText("");
                  jTextField5.setText("");
                  jTextField7.setText("");
                  DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                  model.setColumnCount(0);
                  model.setRowCount(0);
                  if(ret ==0){
                  JOptionPane.showMessageDialog(this,"Unable to insert Bill");
                }
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCustomerInsert.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrmCustomerInsert.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
