/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oss;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author HELLO
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setPreferredSize(new java.awt.Dimension(885, 489));

        jPanel1.setLayout(null);

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setText("Add Products");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(330, 370, 149, 30);

        jLabel12.setText("Payment_Method");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 270, 94, 16);

        jLabel11.setText("Order_date");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 150, 80, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setText("Order Menu");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 20, 280, 48);

        jLabel9.setText("Customer_id");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 230, 67, 16);

        jLabel8.setText("Customer_Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 190, 89, 16);

        jLabel7.setText("Product_Price");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 190, 90, 16);

        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 230, 46, 20);

        jLabel5.setText("Order_id");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 110, 60, 16);

        jLabel4.setText("Product_id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 150, 80, 16);

        jLabel1.setText("Product_Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 110, 79, 20);

        jLabel3.setText("Amount");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 270, 44, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("New order");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 370, 140, 32);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 370, 84, 32);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 110, 150, 20);

        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(200, 150, 150, 22);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(200, 190, 150, 22);

        jTextField6.setEnabled(false);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(200, 230, 150, 22);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(200, 270, 150, 22);

        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(540, 150, 140, 22);

        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(540, 190, 140, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(540, 230, 140, 22);

        jTextField4.setEnabled(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(540, 270, 140, 22);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(540, 110, 140, 22);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oss/2338264.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(-110, 0, 980, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
          try{
            String SQL="SELECT * FROM Products where  P_Name='"+
                    jComboBox1.getSelectedItem()+"'";
                    ResultSet rs = DB_Part.Query(DB_Part.con, SQL);
                    if(rs.next()){
                        jTextField1.setText(String.valueOf(rs.getInt(1)));
                        jTextField2.setText(String.valueOf(rs.getInt(3)));
                    }
         }
           catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     if (jButton1.getText().equals("New order")) {
            jButton1.setText("Submit");
            jTextField1.setText("");
            jTextField6.setText("");
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jButton3.setEnabled(true); 
            try {
                // TODO add your handling code here:
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
                LocalDateTime now = LocalDateTime.now();  
                jTextField5.setText(dtf.format(now));  
                ResultSet rs = DB_Part.Query(DB_Part.con, "SELECT * FROM Customers");
                while(rs.next()) {
                        jComboBox2.addItem(rs.getString(2));
                }
                        jComboBox3.addItem("Cash");
                        jComboBox3.addItem("Card");
                        jComboBox3.addItem("UPI");
               String SQL="Select * from Orders";
               rs = DB_Part.Query(DB_Part.con, SQL);
                if (rs.next()) {
                    rs.last();
                    int id = rs.getInt(1) + 1;
                    jLabel2.setText(String.valueOf(id));
                } else {
                    jLabel2.setText("1");
                }
            }
           catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }
     else{
            jButton1.setText("New order");
            JOptionPane.showMessageDialog(this,"Thank You for Shopping,Please come again");
            jButton3.setEnabled(false);
            jComboBox1.removeAllItems();
            jTextField1.setText("");
            jTextField6.setText("");
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jLabel2.setText("");
            jComboBox2.setEnabled(true);
            jComboBox3.setEnabled(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try{
            String SQL="SELECT * FROM Customers where  C_Name='"+
                    jComboBox2.getSelectedItem()+"'";
                    ResultSet rs = DB_Part.Query(DB_Part.con, SQL);
                    if(rs.next()){
                        jTextField6.setText(String.valueOf(rs.getInt(1)));
                    }
         }
           catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }    
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (jButton3.getText().equals("Add Products")) {
             try {
                 jButton3.setText("Place Order");
                 jTextField1.setText("");
                 jTextField3.setText("");
                 jTextField2.setText("");
                 jTextField4.setText("");
                 jComboBox2.setEnabled(false);
                 jComboBox3.setEnabled(false);
                 // TODO add your handling code here:
                 ResultSet rs = DB_Part.Query(DB_Part.con, "SELECT * FROM Products");
                 while(rs.next()) {
                     jComboBox1.addItem(rs.getString(2));
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
         else{
            jButton3.setText("Add Products");
            int amt=Integer.valueOf(jTextField2.getText())*Integer.valueOf(jTextField3.getText());
            jTextField4.setText(String.valueOf(amt));
            String SQL="INSERT INTO Orders VALUES ('"+jLabel2.getText().trim().toUpperCase()+"','"+jTextField5.getText().trim().toUpperCase()+"','"+jTextField3.getText().trim().toUpperCase()+"','"+jTextField4.getText().trim().toUpperCase()+"','"+jComboBox3.getSelectedItem()+"','"+jTextField1.getText().trim().toUpperCase()+"','"+jTextField6.getText().trim().toUpperCase()+"')";
            if(jLabel2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jComboBox3.getSelectedItem().equals("")||jTextField5.getText().equals("")||jTextField6.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Any field should not be null");
            }
             else{
             try {
              int ret = DB_Part.UpdateTable(DB_Part.con, SQL);
              JOptionPane.showMessageDialog(this,"Order Succesfully Placed");
              jComboBox1.removeAllItems();
              jTextField1.setText("");
              jTextField3.setText("");
              jTextField2.setText("");
              jTextField4.setText("");
              
              if(ret ==0){
                 JOptionPane.showMessageDialog(this,"Unable to insert");
             }
             } catch (SQLException ex) {
                 Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            }
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
          jButton1.setBackground(Color.green);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
          jButton1.setBackground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
          jButton2.setBackground(Color.red);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
          jButton2.setBackground(Color.white);
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
